services:
  # Frontend React app
  - type: web
    name: moodifyme-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 16
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Django app
  - type: web
    name: moodifyme-backend
    env: python
    buildCommand: pip install -r requirements.txt && cd backend && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: moodifyme-db
          property: connectionString
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: moodifyme-db
    databaseName: moodifyme
    user: moodifyme
    plan: free
