services:
  - type: web
    name: moodifyme-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "moodifyme-backend.onrender.com,localhost,127.0.0.1"
      - key: DEBUG
        value: "False"
